on:
  rss:
    url: https://rss.app/feeds/aejPDlFyhRV3EmpC.xml
jobs:
  print:
    name: Lvv2-twitter china group
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-relay.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: jun4rui@gmail.com
          from: jun4rui@gmail.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html