on:
  rss:
    url:
#      - https://lvv2.com/rss/%E6%8E%A8%E7%89%B9%E4%B8%AD%E6%96%87%E5%9C%88
#      - https://rsshub.app/twitter/user/fangshimin
#      - https://rsshub.app/twitter/user/TGTM_Official
#      - https://rsshub.app/twitter/user/willliamlong
      - https://nitter.net/fangshimin/rss
      - https://nitter.net/TGTM_Official/rss
      - https://nitter.net/willliamlong/rss
      - https://rsshub.app/yxdzqb/popular_cn
    config:
      every: "*/15 * * * *"
      debug: false
jobs:
  print:
    name: get rss
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.title }} <hr> ${{ on.rss.outputs.content }} <hr> <a href='${{ on.rss.outputs.link }}' target='_blank'>原文链接</a>
          # Read file contents as body:
          to: jun4rui@gmail.com
          from: jun4rui@gmail.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          secure: true